export const experience = [
  {
    year: "2011",
    period: "09/2011 – 02/2014",
    city: "Hamburg",
    title: "Der Anfang: Technik zum Anfassen.",
    role: "Ausbildung zum IT-Systemelektroniker · Telekom",
    text: "In Hamburg beginnt mein beruflicher Weg in der IT. Infrastruktur nicht nur theoretisch verstehen, sondern praktisch kennenlernen.",
  },
  {
    year: "2014",
    period: "02/2014 – 01/2016",
    city: "Hamburg",
    title: "Dort, wo Technik gebraucht wird.",
    role: "Senior Fachkraft Technik Privatkunden",
    text: "Anschlüsse bereitstellen, Kundenequipment konfigurieren, Störungen beheben. Und erklären, was technisch dahintersteckt.",
  },
  {
    year: "2016",
    period: "01/2016 – 07/2018",
    city: "Hamburg",
    title: "Wenn der Termin nicht warten kann.",
    role: "Messe- und Eventmanagement",
    text: "Cisco LAN und WLAN, Kongresse und Veranstaltungen. Infrastruktur planen und im laufenden Betrieb betreuen.",
  },
  {
    year: "2018",
    period: "Seit 06/2018",
    city: "Bremen",
    title: "Das Ganze im Blick.",
    role: "Operations Manager II · Network & Infrastructure Services",
    text: "2nd- und 3rd-Level-Support, Cisco-Infrastrukturen und Kundenberatung. Dazu Teilprojektleitung sowie Release- und Lifecycle-orientiertes Arbeiten.",
  },
  {
    year: "2026",
    period: "Weiterbildung",
    city: null,
    title: "Neugierig bleiben.",
    role: "Automatisierung & AI",
    text: "Der nächste Blick nach vorn: Cisco AI Technical Practitioner und AIBIZ ergänzen die bisherigen Netzwerk- und Collaboration-Qualifikationen.",
  },
];
